#script=$(realpath "$0")
#script_path=$(dirname "$script")
#source ${script_path}/common.sh
#mysql_root_password=$1
#
#if [ -z "$mysql_root_password" ]; then
#echo Input MySQL Root Password Missing
#exit
#fi
#
#component="shipping"
#schema_setup=mysql
##func_java

- name: Import Common Java
  ansible.builtin.import_role:
    name: common
    tasks_from: java
